import type { Metadata } from "next";
import { Lightbulb, Sparkles, Database, Search, Shield, Zap } from "lucide-react";
import { Badge } from "@/components/ui/Badge";

export const metadata: Metadata = { title: "About" };

export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="text-center mb-12">
        <div className="flex items-center justify-center gap-2 font-heading font-bold text-2xl text-text-primary mb-3">
          <Lightbulb className="w-6 h-6 text-amber-400" />
          About Idea<span className="text-amber-400">Forge</span>
        </div>
        <p className="text-text-secondary leading-relaxed max-w-xl mx-auto">
          IdeaForge is an AI-powered platform helping aspiring entrepreneurs and small manufacturers
          discover, generate, and evaluate validated business ideas.
        </p>
      </div>

      <div className="space-y-8">
        <section>
          <h2 className="text-xl font-bold font-heading text-text-primary mb-4">The Problem We Solve</h2>
          <p className="text-text-secondary leading-relaxed">
            Platforms like IdeaBrowser and 10000ideas.com offer static idea lists — you browse, you read, you move on.
            There's no way to generate ideas tailored to your specific niche, no AI to answer questions about the database,
            and no personalized recommendations. IdeaForge turns passive browsing into active idea creation.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold font-heading text-text-primary mb-4">AI Capabilities</h2>
          <div className="space-y-4">
            {[
              {
                icon: Sparkles, color: "text-violet-400", bg: "bg-violet-500/10",
                title: "AI Idea Generator (Gemini 2.0 Flash)",
                desc: "Enter any niche or keyword → Gemini generates a structured idea report: problem, solution, target market, revenue model, feasibility score, competitive landscape, and 5-step roadmap.",
              },
              {
                icon: Search, color: "text-violet-400", bg: "bg-violet-500/10",
                title: "RAG-Based AI Search (ChromaDB + Gemini Embeddings)",
                desc: "Ask natural-language questions about the idea database. Answers are retrieved by embedding similarity then generated by Gemini, with citations to source ideas.",
              },
              {
                icon: Database, color: "text-amber-400", bg: "bg-amber-500/10",
                title: "Content-Based Recommendation Engine (TF-IDF)",
                desc: "Suggests related ideas based on TF-IDF cosine similarity to your saved ideas. Lightweight, explainable, no ML training pipeline required.",
              },
            ].map((f) => (
              <div key={f.title} className="bg-surface-DEFAULT border border-surface-border rounded-xl p-5">
                <div className={`w-8 h-8 rounded-lg ${f.bg} flex items-center justify-center mb-3`}>
                  <f.icon className={`w-4 h-4 ${f.color}`} />
                </div>
                <h3 className="font-semibold font-heading text-text-primary mb-1">{f.title}</h3>
                <p className="text-sm text-text-secondary leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold font-heading text-text-primary mb-4">What We Deliberately Don't Use</h2>
          <p className="text-sm text-text-secondary mb-3">
            The domain is purely textual/structured idea data with no image, audio, or time-series inputs.
            The following AI capabilities were considered and excluded:
          </p>
          <div className="flex flex-wrap gap-2">
            {["Computer Vision", "OCR", "Speech-to-Text", "Text-to-Speech", "Predictive Time-Series Analytics"].map((t) => (
              <Badge key={t} variant="outline" className="opacity-50">{t} — not applicable</Badge>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold font-heading text-text-primary mb-4">Tech Stack</h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
            {[
              "Next.js 14 (App Router)", "FastAPI (Python 3.11)", "PostgreSQL",
              "ChromaDB (Vector Store)", "Gemini 2.0 Flash", "Gemini Embedding 001",
              "LangChain", "SQLAlchemy + Alembic", "JWT Auth (httpOnly cookies)",
            ].map((t) => (
              <div key={t} className="bg-surface-DEFAULT border border-surface-border rounded-lg px-3 py-2 text-sm text-text-secondary text-center">
                {t}
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold font-heading text-text-primary mb-4">Security & Scalability</h2>
          <div className="bg-surface-DEFAULT border border-surface-border rounded-xl p-5 space-y-2 text-sm text-text-secondary">
            <div className="flex items-center gap-2"><Shield className="w-4 h-4 text-amber-400 shrink-0" /> JWT access tokens (30 min) + refresh tokens (7 days) in httpOnly cookies</div>
            <div className="flex items-center gap-2"><Shield className="w-4 h-4 text-amber-400 shrink-0" /> bcrypt password hashing, parameterized queries (SQLAlchemy ORM)</div>
            <div className="flex items-center gap-2"><Shield className="w-4 h-4 text-amber-400 shrink-0" /> Role-based access control (guest / user / admin)</div>
            <div className="flex items-center gap-2"><Zap className="w-4 h-4 text-violet-400 shrink-0" /> AI Generator rate-limited (10/day per user) to control API costs</div>
            <div className="flex items-center gap-2"><Zap className="w-4 h-4 text-violet-400 shrink-0" /> AI Generator results cached — identical prompts skip Gemini call</div>
            <div className="flex items-center gap-2"><Zap className="w-4 h-4 text-violet-400 shrink-0" /> /admin/reindex endpoint to rebuild ChromaDB from Postgres on demand</div>
          </div>
        </section>
      </div>
    </div>
  );
}
